TrajectoryPlannerROS:
  acc_lim_x: 5
  acc_lim_y: 5
  acc_lim_theta: 3.2
  max_vel_x: 3
  min_vel_x: 0.2
  max_vel_theta: 2.0
  min_vel_theta: -2.0
  min_in_place_vel_theta: 0.4
  escape_vel: -0.1
  holonomic_robot: false 
  y_vels: [-0.5,-0.3, -0.1, 0.1, 0.3,0.5]

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  sim_time: 3.0
  sim_granularity: 0.025 
  vx_samples: 30
  vtheta_samples: 40

  meter_scoring: false
  pdist_scale: 2
  gdist_scale: 0.7
  occdist_scale: 0.1
  heading_lookahead: 0.325
  heading_scoring: 0.8
  dwa: true
  publish_cost_grid_pc: false
  global_frame_id: odom

