EBandPlannerROS:
# Common: 
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 1

    rot_stopped_vel: 0.05
    trans_stopped_vel: 0.01

# Elastic Band Parameters: 0.7
    eband_min_relative_overlap: 0.7
    eband_tiny_bubble_distance: 0.01
    eband_tiny_bubble_expansion: 0.01
    eband_internal_force_gain: 1.0
    eband_external_force_gain: 2.0
    num_iterations_eband_optimization: 3
    eband_equilibrium_approx_max_recursion_depth: 4
    eband_equilibrium_relative_overshoot: 0.75
    eband_significant_force_lower_bound: 0.15
    costmap_weight: 20.0

# Trajectory Controller Parameters: 
    max_vel_lin: 1
    max_vel_th: 0.75

    min_vel_lin: 0.2
    min_vel_th: 0.01

    min_in_place_vel_th: 0.05
    in_place_trans_vel: 0.1

    k_prop: 4
    k_damp: 3.8

    Ctrl_Rate: 10

    max_acceleration: 1.5
    virtual_mass: 1

    max_translational_acceleration: 2

    max_rotational_acceleration: 2.2

    rotation_correction_threshold: 0.5

    differential_drive: True
    bubble_velocity_multiplier: 2.0
    rotation_threshold_multiplier: 1.0
    disallow_hysteresis: False
