global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 5.0
  static_map: true
  transform_tolerance: 1.5
#  reset_distance: 1.5
  inflation_radius: 0.55
  cost_scaling_factor: 10.0
